server:
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
    session:
      tracking-modes: COOKIE
      timeout: 30m
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp